### ISSUE TITLE
Add MicroByte for JWT

### ISSUE THREAD

**Issue by DesignrKnight** [Crio-Bytes/Security#1]
**MicroByte Title:**: Understanding JWT

**Domain:** 
- Security
- Auth

**Scope of learning for learners:** 
- Understand working and importance of JWT
- Learn to parse a JWT on their own

**Activities:** 
- Parse JWT to get the message, 
- Try Modifying JWT to show that tampering voids the JWT
- Create own JWT with a custom message

**Comment by DesignrKnight** [comment]
Planning to finish within the next 2-3 days!

**Comment by YourAKShaw** [comment]
@DesignrKnight Kindly refer to this issue https://github.com/Crio-Bytes/Miscellaneous/issues/3.
**_Point to be noted:_** You need to mention all in bullet points. Kindly edit your issue description to incorporate the proper changes.

**Comment by DesignrKnight** [comment]
Thanks for the feedback. Have done the same

**Comment by YourAKShaw** [comment]
Cool. It seems decent. Looking forward to your PR!

**Comment by sudhanshutiwari264** [comment]
@DesignrKnight Assigning it to you!
We apologize for the late reaction!
Waiting for your contribution!
